version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  springboot-app:
    build: .
    container_name: my-mongodb-springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: book
    restart: unless-stopped

volumes:
  mongo-data:
